---
title: "Analysis of Wines"
author: "PJ Taal"
date: "2025-05-31"
output: html_document
editor_options: 
  chunk_output_type: console
---

library zoo

```{r}
library(dplyr)
library(tidyverse)
library(DataExplorer)
library(corrplot)
library(tidyr)
library(dplyr)
library(ggplot2)
```

Read in Data

```{r}
#The delimiter used in the original datasets are delimited by a semi-colon instead of a comma as is typical
rd <- read.csv("winequality-red.csv", sep = ";")

wt <- read.csv("winequality-white.csv",sep = ";")
```

Combine the datasets 
```{r}
identical(names(rd),names(wt))


df_wr <- bind_rows(
  rd %>% mutate(is_rd = TRUE),
  wt %>% mutate(is_rd = FALSE)   
)


```

Initital Sandbox


```{r}
str(df_wr)
glimpse(df_wr)
names(df_wr) <- gsub("\\.", 
                     "_",
                     names(df_wr))


summary(df_wr)
plot_histogram(df_wr)
create_report(df_wr)


correlation_matrix <- cor(df_wr[, sapply(df_wr, is.numeric)], use = "complete.obs")
corrplot(correlation_matrix, method = "circle")

plot(df_wr$alcohol,df_wr$density)
plot(df_wr$density,df_wr$fixed.acidity)
plot(df_wr$density,df_wr$residual.sugar)
plot(df_wr$residual.sugar,df_wr$total.sulfur.dioxide)
plot(df_wr$sulphates,df_wr$chlorides) 

x <- lm(alcohol~density, data = df_wr)
summary(x)


plot(df_wr$density, df_wr$alcohol,
  main = "Linear regression of Alcohol on desity" 
)

```



